### ISSUE TITLE
enable prebuild support

### ISSUE THREAD

**Issue by shiftkey** [atom/fs-admin#11]
See these links for how `keytar` has it configured:

 - https://github.com/atom/node-keytar/blob/master/package.json#L37-L40

 - https://github.com/atom/node-keytar/blob/f282c0135cb1f9b62c187af1240ab324b0139305/appveyor.yml#L21-L27

 - https://github.com/atom/node-keytar/blob/f282c0135cb1f9b62c187af1240ab324b0139305/.travis.yml#L47-L52

**Comment by shiftkey** [comment]
This was implemented in #13 and is now available in the [`v0.9.0`](https://github.com/atom/fs-admin/releases/tag/v0.9.0) update on NPM.

**Comment by Semulv** [comment]
#> > See these links for how `keytar` has it configured:
> > 
> > * https://github.com/atom/node-keytar/blob/master/package.json#L37-L40
> > * https://github.com/atom/node-keytar/blob/f282c0135cb1f9b62c187af1240ab324b0139305/appveyor.yml#L21-L27
> > * https://github.com/atom/node-keytar/blob/f282c0135cb1f9b62c187af1240ab324b0139305/.travis.yml#L47-L52
> 
>
